### ISSUE TITLE
Failed to load the atom-jshinter package

### ISSUE THREAD

**Issue by esouto** [gerred/atom-jshinter#4]
[Enter steps to reproduce below:]
1. ...
2. ...

**Atom Version**: 0.194.0 :warning: **in 1.0 API Preview Mode** :warning:
**System**: Mac OS X 10.10.3
**Thrown From**: [atom-jshinter](https://github.com/gerred/atom-jshinter) package, v0.1.3
### Stack Trace

Failed to load the atom-jshinter package

```
At Cannot read property 'prototype' of undefined

TypeError: Cannot read property 'prototype' of undefined
    at __extends (/Users/Eduardo/.atom/packages/atom-jshinter/lib/icon-view.coffee:4:199)
    at /Users/Eduardo/.atom/packages/atom-jshinter/lib/icon-view.coffee:9:5
    at Object.<anonymous> (/Users/Eduardo/.atom/packages/atom-jshinter/lib/icon-view.coffee:24:5)
    at Object.<anonymous> (/Users/Eduardo/.atom/packages/atom-jshinter/lib/icon-view.coffee:26:4)
    at Module._compile (module.js:452:26)
    at Object.requireCoffeeScript (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/coffee-cash/lib/coffee-cash.js:85:19)
    at Module.load (module.js:347:32)
    at Function.Module._load (module.js:302:12)
    at Module.require (module.js:357:17)
    at require (module.js:376:17)
```
### Commands

```
```
### Config

``` json
{
  "core": {
    "followSymlinks": true,
    "themes": [
      "one-dark-ui",
      "one-light-syntax"
    ]
  }
}
```
### Installed Packages

``` coffee
# User
Atom-Syntax-highlighting-for-Sass, v0.5.0
atom-jshinter, v0.1.3
autocomplete-paths, v1.0.2
emmet, v2.3.8
file-icons, v1.5.4
git-history, v2.5.0
git-log, v0.3.0
git-tab-status, v1.7.0
key-peek, v0.2.5
language-aspx, v0.4.0
linter, v0.12.1
minimap, v4.7.6
sassbeautify, v0.2.0
tasks, v2.0.0
tree-view-open-files, v0.2.3

# Dev
No dev packages
```

**Comment by esouto** [comment]
[Enter steps to reproduce below:]
1. ...
2. ...

**Atom Version**: 0.211.0
**System**: Mac OS X 10.10.3
**Thrown From**: [atom-jshinter](https://github.com/gerred/atom-jshinter) package, v0.1.3

### Stack Trace

Failed to load the atom-jshinter package

```
At Cannot read property 'prototype' of undefined

TypeError: Cannot read property 'prototype' of undefined
    at __extends (/Users/Eduardo/.atom/packages/atom-jshinter/lib/icon-view.coffee:4:199)
    at /Users/Eduardo/.atom/packages/atom-jshinter/lib/icon-view.coffee:9:5
    at Object.<anonymous> (/Users/Eduardo/.atom/packages/atom-jshinter/lib/icon-view.coffee:24:5)
    at Object.<anonymous> (/Users/Eduardo/.atom/packages/atom-jshinter/lib/icon-view.coffee:26:4)
    at Module._compile (module.js:452:26)
    at Object.requireCoffeeScript (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/coffee-cash/lib/coffee-cash.js:85:19)
    at Module.load (module.js:347:32)
    at Function.Module._load (module.js:302:12)
    at Module.require (module.js:357:17)
    at require (module.js:376:17)
```

### Commands

```
```

### Config

``` json
{
  "core": {
    "followSymlinks": true,
    "themes": [
      "one-dark-ui",
      "one-light-syntax"
    ]
  }
}
```

### Installed Packages

``` coffee
# User
Atom-Syntax-highlighting-for-Sass, v0.5.0
atom-jshinter, v0.1.3
autocomplete-paths, v1.0.2
emmet, v2.3.10
file-icons, v1.5.8
git-log, v0.4.1
git-tab-status, v1.9.2
language-aspx, v0.4.0
linter, v1.0.6
minimap, v4.10.0
tasks, v2.1.0
tree-view-open-files, v0.2.4

# Dev
No dev packages
```

**Comment by esouto** [comment]
[Enter steps to reproduce below:]
1. ...
2. ...

**Atom Version**: 1.0.0
**System**: Mac OS X 10.10.4
**Thrown From**: [atom-jshinter](https://github.com/gerred/atom-jshinter) package, v0.1.3

### Stack Trace

Failed to load the atom-jshinter package

```
At Cannot read property 'prototype' of undefined

TypeError: Cannot read property 'prototype' of undefined
    at __extends (/Users/Eduardo/.atom/packages/atom-jshinter/lib/icon-view.coffee:4:199)
    at /Users/Eduardo/.atom/packages/atom-jshinter/lib/icon-view.coffee:9:5
    at Object.<anonymous> (/Users/Eduardo/.atom/packages/atom-jshinter/lib/icon-view.coffee:24:5)
    at Object.<anonymous> (/Users/Eduardo/.atom/packages/atom-jshinter/lib/icon-view.coffee:26:4)
    at Module._compile (module.js:452:26)
    at Object.requireCoffeeScript (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/coffee-cash/lib/coffee-cash.js:85:19)
    at Module.load (module.js:347:32)
    at Function.Module._load (module.js:302:12)
    at Module.require (module.js:357:17)
    at require (module.js:376:17)
```

### Commands

```
     -0:00.7.0 linter:set-bubble-transparent (atom-text-editor.editor)
```

### Config

``` json
{
  "core": {
    "followSymlinks": true
  }
}
```

### Installed Packages

``` coffee
# User
Atom-Syntax-highlighting-for-Sass, v0.5.0
atom-jshinter, v0.1.3
autocomplete-paths, v1.0.2
emmet, v2.3.12
file-icons, v1.5.8
git-log, v0.4.1
git-tab-status, v1.9.2
language-aspx, v0.4.0
linter, v1.1.0
minimap, v4.10.2
tasks, v2.1.0
tree-view-open-files, v0.2.4

# Dev
No dev packages
```

**Comment by skyperx** [comment]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.46.0 x64
**Electron**: 4.2.7
**OS**: Unknown Windows version
**Thrown From**: [atom-jshinter](https://github.com/gerred/atom-jshinter) package 0.1.3


### Stack Trace

Failed to load the atom-jshinter package

```
At Cannot read property 'prototype' of undefined

TypeError: Cannot read property 'prototype' of undefined
    at extend (/packages/atom-jshinter/lib/icon-view.coffee:1:1)
    at /packages/atom-jshinter/lib/icon-view.coffee:3:24
    at /packages/atom-jshinter/lib/icon-view.coffee:4:13)
    at /packages/atom-jshinter/lib/icon-view.coffee:1:1)
    at /packages/atom-jshinter/lib/icon-view.coffee:1:1)
    at Module.get_Module._compile (~/AppData/Local/atom/app-1.46.0/resources/app/static/<embedded>:11:147429)
    at Object.value [as .coffee] (~/AppData/Local/atom/app-1.46.0/resources/app/static/<embedded>:11:150977)
    at Module.load (internal/modules/cjs/loader.js:602:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:541:12)
    at Function.Module._load (internal/modules/cjs/loader.js:533:3)
    at Module.require (/app.asar/static/index.js:72:46)
    at require (~/AppData/Local/atom/app-1.46.0/resources/app/static/<embedded>:11:146745)
    at /packages/atom-jshinter/lib/atom-jshinter.coffee:5:12)
    at /packages/atom-jshinter/lib/atom-jshinter.coffee:1:1)
    at /packages/atom-jshinter/lib/atom-jshinter.coffee:1:1)
    at Module.get_Module._compile (~/AppData/Local/atom/app-1.46.0/resources/app/static/<embedded>:11:147429)
    at Object.value [as .coffee] (~/AppData/Local/atom/app-1.46.0/resources/app/static/<embedded>:11:150977)
    at Module.load (internal/modules/cjs/loader.js:602:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:541:12)
    at Function.Module._load (internal/modules/cjs/loader.js:533:3)
    at Module.require (/app.asar/static/index.js:72:46)
    at require (internal/modules/cjs/helpers.js:20:18)
    at customRequire (~/AppData/Local/atom/app-1.46.0/resources/app/static/<embedded>:1:721712)
    at Package.requireMainModule (~/AppData/Local/atom/app-1.46.0/resources/app/static/<embedded>:11:3299000)
    at measure (~/AppData/Local/atom/app-1.46.0/resources/app/static/<embedded>:11:3285540)
    at Package.measure (~/AppData/Local/atom/app-1.46.0/resources/app/static/<embedded>:11:3284372)
    at Package.load (~/AppData/Local/atom/app-1.46.0/resources/app/static/<embedded>:11:3285113)
    at PackageManager.loadAvailablePackage (~/AppData/Local/atom/app-1.46.0/resources/app/static/<embedded>:11:381274)
    at PackageManager.loadPackage (~/AppData/Local/atom/app-1.46.0/resources/app/static/<embedded>:11:380002)
    at PackageManager.activatePackage (~/AppData/Local/atom/app-1.46.0/resources/app/static/<embedded>:11:382574)
    at ~/AppData/Local/atom/app-1.46.0/resources/app/static/<embedded>:11:943557
    at r (~/AppData/Local/atom/app-1.46.0/resources/app/static/<embedded>:11:938163)
    at o (~/AppData/Local/atom/app-1.46.0/resources/app/static/<embedded>:14:1122275)
    at ChildProcess.n.process.on.e (~/AppData/Local/atom/app-1.46.0/resources/app/static/<embedded>:14:1122481)
    at ChildProcess.emit (events.js:182:13)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:240:12)
```

### Commands

```
  4x -7:15.5.0 core:move-down (atom-pane.pane.active)
 10x -6:27.3.0 core:backspace (input.hidden-input)
 27x -6:03.4.0 core:move-down (button.btn.btn-default.selected)
  2x -5:34 core:move-up (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-one-dark-ui)
undefined -5:32.8.0 core:move-down (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-one-dark-ui)
```

### Non-Core Packages

```
atom-clock 0.1.18 
atom-jshinter 0.1.3 
autocomplete-ansible 0.1.25 
brackets 0.5.0 
busy-signal 2.0.1 
c-header-generator 0.2.0 
header-42 0.3.3 
hide-files 0.3.0 
html-presets 1.1.2 
Hydrogen 2.14.1 
switch-header-source 0.34.1 
```
